### ISSUE TITLE
task_before报错

### ISSUE THREAD

**Issue by free-diy** [q398044828/xxoo_share_pool#2]
## 开始执行... 2021-11-14 15:30:54

/ql/log/xxoo/2021-11-14-15-15-55.log: line 101: $'\r': command not found
/ql/log/xxoo/2021-11-14-15-15-55.log: line 103: $'\r': command not found
##  xxoo助力池同步时间===========》 2021年11月14日 15:15:59

#【15:30:54】 当前 code.sh 的线程数量：4

#【15:30:54】 预设的 JD_COOKIE 数量：10

#【15:30:54】 预设的 JD_COOKIE 环境变量数量：10

#【15:30:54】 从日志提取互助码，编号和配置文件中Cookie编号完全对应，如果为空就是所有日志中都没有。

#【15:30:54】 即使某个MyXxx变量未赋值，也可以将其变量名填在ForOtherXxx中，jtask脚本会自动过滤空值。

#【15:30:54】 您选择的互助码模板为：所有账号机会均等助力。

**Comment by Michaol** [comment]
你复制脚本有问题，自己加入了"\r"换行符

**Comment by q398044828** [comment]
已修复
